apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
    team: voting-app
    env: production
  name: vote
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
        team: voting-app
        env: production
    spec:
      containers:
      - image: dockersamples/examplevotingapp_vote
        name: vote
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: vote
